# Docker Compose for Laravel + Node + SQLite

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: job-board-main-app
    container_name: job-board-main-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      #- .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_KEY=base64:YOUR_APP_KEY_HERE
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    ports:
      - "8000:8000"
    depends_on:
      - node
    command: bash -c "rm -f /var/www/html/database/database.sqlite && touch /var/www/html/database/database.sqlite && composer install && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000"

  node:
    image: node:22
    container_name: job-board-node-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - VITE_APP_URL=${APP_URL}
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"

volumes:
  storage:
    driver: local
